# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico
# Content configuration version
version: 2

# Personal info
name: Wulf Novak  
title: Data Scientist
email: wulfnovak@gmail.com
#website: www.github.com/sproogen/resume-theme # unsure what to place here /wulfnovak/resume-theme?

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: facespics
github_username:  wulfnovak
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: wulf-novak
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: Job Search
#about_profile_image: images/profile.jpg # consider omitting to prevent bias
about_content: | # this will include new lines to allow paragraphs
  Complementary to my resume, this simple website explains the recent gap on my resume and several projects undertaken while unemployed. 
  Though my resume and projects may not match the perfect candidate, I am happy to build skills that solve your team’s needs.
  
  At my previous role, a Data Scientist at E Source, one of the techniques I used to select the number of clusters for a clustering algorithm was disputed, 
  and I was let go. Though I lost the opportunity to challenge and collaborate with colleagues, I gained time to begin in an area I was lacking; Python. 
  Since then, I have improved drastically at Python, SQL, and learned through experimentation - the following are some projects showing that work. 

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
      - title: Meta Transaction Risk Classification
        additional_links:
          - title:  github.com/wulfnovak/Meta-Transaction-Risk-Classification
            icon: fab fa-github
            url: github.com/wulfnovak/Meta-Transaction-Risk-Classification
        description: | # this will include new lines to allow paragraphs
          This notebook analyzes pre-cleaned and simulated meta transaction data, 
          tests 4 model types with a range of hyperparameters
          utilizing Halving Grid Search and Bayesian Optimization. I then build a model
          pipeline that cross validates and fine-tunes models. The results are discussed 
          and final Voting and Stacking ensembles are compared with the initial models. 

          - <a href="https://github.com/WulfNovak/Meta-Transaction-Risk-Classification/blob/main/meta_ensemble_pipeline.ipynb">Here is the notebook for the model pipeline </a> 
       
          Key Skills: <mark>Python</mark>, <mark>Scikit Learn</mark>, <mark>Pandas</mark>, <mark>Seaborn</mark>, <mark>Numpy</mark>, <mark>LightGBM</mark>

      - title: Rising or Declining Country Emissions
        #link: https://github.com/WulfNovak/Rising-Or-Declining-Country-Emissions
        # link_text: Project Website
        additional_links:
          - title:  github.com/WulfNovak/Rising-Or-Declining-Country-Emissions
            icon: fab fa-github
            url: https://github.com/WulfNovak/Rising-Or-Declining-Country-Emissions
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        # quote: >
        #   Data Analysis in R 
        description: | # this will include new lines to allow paragraphs
          Written in R, this project categorizes countries as having rising or declining emissions from 2000-2022. 
          Two methods are used, one which relies on there being a significant linear trend over the 
          time period, and another that relies on longitudinal clustering. Both give similar results.
      
          - <a href="https://wulfnovak.github.io/country_emissions/">A simple html/css website was created to show interactive choropleth world maps. </a> 
              
          Key Skills: <mark>R</mark>, <mark>tidyverse</mark>, <mark>plotly</mark>, <mark>leaflet</mark>, <mark>gganimate</mark>, <mark>data visualization</mark>, <mark>longitudinal clustering</mark>
          
      - title: Python Data Cleaning
        #link: https://github.com/WulfNovak/Rising-Or-Declining-Country-Emissions
        # link_text: Project Website
        additional_links:
          - title:  github.com/WulfNovak/python_data_cleaning
            icon: fab fa-github
            url: https://github.com/WulfNovak/python_data_cleaning
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        # quote: >
        #   Data Analysis in R 
        description: | # this will include new lines to allow paragraphs
          Analyzed Alzheimers Disease and Health Aging Data, providing functions that: 
          1) Generate statistics for variables of interest and missing data, 
          2) imputes data at the stratum level, and 3) visualizes data 
          by given question and stratum over time.
       
          Key Skills: <mark>Pandas</mark>, <mark>Numpy</mark>, <mark>SeaBorn</mark>

      - title: Time Series Model Comparison
        #link: https://github.com/WulfNovak/Rising-Or-Declining-Country-Emissions
        # link_text: Project Website
        additional_links:
          - title:  github.com/WulfNovak/time_series_model_comparison
            icon: fab fa-github
            url: https://github.com/WulfNovak/time_series_model_comparison
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        # quote: >
        #   Data Analysis in R 
        description: | # this will include new lines to allow paragraphs
          A brief forray into Deep Learning with an LSTM time series prediction. I then create a grid search to 
          test optimal parameters for the model, storing the results. 
       
          Key Skills: <mark>Deep Learning</mark>, <mark>Scikit Learn</mark>, <mark>tensorflow</mark>, <mark>keras</mark>, <mark>pandas</mark>



  # - title: Experience # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: left
  #       title: E Source
  #       link: https://www.esource.com/
  #       link_text: Boulder, Colorado
  #       sub_title: Data Scientist
  #       caption: April 2022 - November 2023
  #       quote: >
  #         May leave this section blank
  #       description: | # this will include new lines to allow paragraphs
  #         May give alternate description to resume bullet points. But for now: 
            
  #         ● Built ETL pipelines to convene, clean, and engineer features from high-dimensional data across millions of utility customers and premises.
            
  #         ● Developed fine-tuned model pipelines to give premise level predictions, classify end-use, and cluster customer program impact profiles.
            
  #         ● Led collaboration with data engineering that improved critical premise append matching algorithm’s accuracy 14% and accelerated processing time by 6x.
            
  #         ● Developed and automated data ingestion for interactive dashboard that monitored high volume Advanced Meter Infrastructure data, facilitating daily insight into client data quality.
            
  #         ● Created informative and story driven presentations, with key decisions emphasized by statistics and clear visualizations, giving clients understanding of methodology and results.
  #     #content:
  #     -  layout: left
  #        title: Wiland
  #        link: https://wiland.com/
  #        link_text: Niwot, Colorado # can this be called location instead? 
  #        sub_title: Client Solutions Statistician
  #        caption: June 2019 - November 2021
  #        quote: >
  #          May leave this section blank
  #        description: | 
  #          ● Collaborated cross-functionally to resolve bottlenecks and drive high priority client work, leading to urgent deadlines being met. 
           
  #          ● Built automated analytical tools and reports to inform clients about their customers and marketing campaign performance. 
           
  #          ● Utilized machine learning (elastic net, random forest, xgboost) for 300+ clients, predicting response rate and total dollars for marketing campaigns. 
           
  #          ● Consulted sales and clients on customized models and campaign strategy decisions, designing data-driven strategies to maximize client growth.

  # - title: Education # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: left
  #       title: Colorado State University
  #       caption: 2016 - 2019
  #       sub_title: BSc Statistics
  #       quote: >
  #         Probably remove this quote section
  #       description: | # this will include new lines to allow paragraphs
  #         Dean's List - Vice President of the Statistics Club

  - title: About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Much of my time is devoted to bettering my programming ability and learning new machine learning techniques, but that's not all that I do!
      I also listen and collaborate as a volunteer in community bands and enjoy the consistent challenge of triathlon.
    # I have volunteered as a saxophonist in community orchestra, concert, and jazz bands, and seek to complete a half-ironman in this next year. 
    #  - Work/Study in local coffee shops

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
