# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Wulf Novak  
title: Data Scientist
email: wulfnovak@gmail.com
#website: www.github.com/sproogen/resume-theme # unsure what to place here /wulfnovak/resume-theme?

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: facespics
github_username:  wulfnovak
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: wulf-novak
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello My name is Wulf Novak, and I am really serious. This is my serious resume website. I may need to update this content section with something both MORE and less serious. 

  I am most skilled in: <mark>Python</mark>, <mark>SQL</mark>, <mark>R</mark> and <mark>Machine Learning</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
      - title: Meta Transaction Risk Classification
        #link: https://github.com/WulfNovak/Rising-Or-Declining-Country-Emissions
        # link_text: Project Website
        additional_links:
          - title:  wulfnovak/Meta-Transaction-Risk-Classification
            icon: fab fa-github
            url: github.com/wulfnovak/Meta-Transaction-Risk-Classification
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        # quote: >
        #   Data Analysis in R 
        description: | # this will include new lines to allow paragraphs
          This notebook analyzes pre-cleaned and simulated meta transaction data, 
          tests 4 model types with a range of hyperparameters
          utilizing Halving Grid Search and Bayesian Optimization. The implementation is general
          and can easily be adapted to most any model available in scikit learn. Though not 
          advisable given the input models, I then test Stacking and Voting classifiers as 
          ensemble models. 
       
          Key Skills: <mark>Python</mark>, <mark>Scikit Learn</mark>, <mark>Pandas</mark>, <mark>Seaborn</mark>, <mark>Numpy</mark>, <mark>LightGBM</mark>, <mark>Machine Learning Pipeline</mark>
        # title: Meta Transaction Risk Classification
        # link: github.com/wulfnovak
        # # link_text: Project Website
        # additional_links:
        #   - title:  wulfnovak/Meta-Transaction-Risk-Classification
        #     icon: fab fa-github
        #     url: github.com/wulfnovak/Meta-Transaction-Risk-Classification
        #   # - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #   #   icon: fab fa-github
        #   #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        # quote: >
        #   First Project in Python 
        # description: | # this will include new lines to allow paragraphs
        #   This notebook analyzes pre-cleaned and simulated meta transaction data, 
        #   tests 4 model types with a range of hyperparameters
        #   utilizing Halving Grid Search and Bayesian Optimization. The implementation is general
        #   and can easily be adapted to most any model available in scikit learn. Though not 
        #   advisable given the input models, I then test Stacking and Voting classifiers as 
        #   ensemble models. 

        #   Key Skills: <mark>Python</mark>, <mark>Scikit Learn</mark>, <mark>Pandas</mark>, <mark>Seaborn</mark>, <mark>Numpy</mark>, <mark>LightGBM</mark>, <mark>Machine Learning Pipeline</mark>

      #- layout: top-middle # top-middle, top-bottom
      - title: Rising or Declining Country Emissions
        #link: https://github.com/WulfNovak/Rising-Or-Declining-Country-Emissions
        # link_text: Project Website
        additional_links:
          - title:  wulfnovak/Meta-Transaction-Risk-Classification
            icon: fab fa-github
            url: https://github.com/WulfNovak/Rising-Or-Declining-Country-Emissions
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        # quote: >
        #   Data Analysis in R 
        description: | # this will include new lines to allow paragraphs
          This project categorizes countries as having rising or declining emissions from 2000-2022. 
          Two methods are used, one which relies on there being a significant linear trend over the 
          time period, and another that relies on longitudinal clustering. Both give similar results.

          A simple html/css website was created to show interactive choropleth world maps. This can be found here:
          [Rebuilding https://wulfnovak.github.io/, will re-add website shortly]
       
          Key Skills: <mark>R</mark>, <mark>tidyverse</mark>, <mark>plotly</mark>, <mark>leaflet</mark>, <mark>gganimate</mark>, <mark>data visualization</mark>, <mark>longitudinal clustering</mark>

      - title: Time Series Model Comparison
        #link: https://github.com/WulfNovak/Rising-Or-Declining-Country-Emissions
        # link_text: Project Website
        additional_links:
          - title:  wulfnovak/Time-Series-Model-Comparison
            icon: fab fa-github
            url: https://github.com/WulfNovak/time_series_model_comparison
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        # quote: >
        #   Data Analysis in R 
        description: | # this will include new lines to allow paragraphs
          LSTM time series prediction, along with automated grid search and saving of model weights.
          
          More to come.
       
          Key Skills: <mark>Deep Learning</mark>, <mark>Scikit Learn</mark>, <mark>tensorflow</mark>, <mark>keras</mark>, <mark>pandas</mark>

      - title: Python Data Cleaning
        #link: https://github.com/WulfNovak/Rising-Or-Declining-Country-Emissions
        # link_text: Project Website
        additional_links:
          - title:  wulfnovak/Time-Series-Model-Comparison
            icon: fab fa-github
            url: https://github.com/WulfNovak/python_data_cleaning
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        # quote: >
        #   Data Analysis in R 
        description: | # this will include new lines to allow paragraphs
          Analyzes Alzheimers Disease and Health Again Data and provides functions that 
          1. analyze variables of interest, 2. analyze missing data, 3. imputes date (opted against using), 
          4. visualizes data by given question and stratum over time
       
          Key Skills: <mark>Pandas</mark>, <mark>Numpy</mark>, <mark>SeaBorn</mark>

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: E Source
        link: https://www.esource.com/
        link_text: Boulder, Colorado
        sub_title: Data Scientist
        caption: April 2022 - November 2023
        quote: >
          May leave this section blank
        description: | # this will include new lines to allow paragraphs
          May give alternate description to resume bullet points. But for now: 
            
          ● Built ETL pipelines to convene, clean, and engineer features from high-dimensional data across millions of utility customers and premises.
            
          ● Developed fine-tuned model pipelines to give premise level predictions, classify end-use, and cluster customer program impact profiles.
            
          ● Led collaboration with data engineering that improved critical premise append matching algorithm’s accuracy 14% and accelerated processing time by 6x.
            
          ● Developed and automated data ingestion for interactive dashboard that monitored high volume Advanced Meter Infrastructure data, facilitating daily insight into client data quality.
            
          ● Created informative and story driven presentations, with key decisions emphasized by statistics and clear visualizations, giving clients understanding of methodology and results.
      #content:
      -  layout: left
         title: Wiland
         link: https://wiland.com/
         link_text: Niwot, Colorado # can this be called location instead? 
         sub_title: Client Solutions Statistician
         caption: June 2019 - November 2021
         quote: >
           May leave this section blank
         description: | 
           ● Collaborated cross-functionally to resolve bottlenecks and drive high priority client work, leading to urgent deadlines being met. 
           
           ● Built automated analytical tools and reports to inform clients about their customers and marketing campaign performance. 
           
           ● Utilized machine learning (elastic net, random forest, xgboost) for 300+ clients, predicting response rate and total dollars for marketing campaigns. 
           
           ● Consulted sales and clients on customized models and campaign strategy decisions, designing data-driven strategies to maximize client growth.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Colorado State University
        caption: 2016 - 2019
        sub_title: BSc Statistics
        quote: >
          Probably remove this quote section
        description: | # this will include new lines to allow paragraphs
          Dean's List - Vice President of the Statistics Club

  - title: About Me Section
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in programming, machine learning, and organizations. 
      - There will be a Leetcode Section
      - There will be a Leetcode Section
      - There will be a Leetcode Section
      - Triathlon

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
