# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Wulf Novak  
title: Data Scientist
email: wulfnovak@gmail.com
website: www.github.com/sproogen/resume-theme # unsure what to place here /wulfnovak/resume-theme?

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: facespics
github_username:  wulfnovak
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: wulf-novak
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello My name is Wulf Novak, and I am really serious. This is my serious resume website. I may need to update this content section with something both MORE and less serious. 

  I am most skilled in: <mark>Python</mark>, <mark>SQL</mark>, <mark>R</mark> and <mark>Machine Learning</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Python Project
        link: github.com/wulfnovak
        # link_text: Project Website
        additional_links:
          - title:  wulfnovak/Meta-Transaction-Risk-Classification
            icon: fab fa-github
            url: github.com/sproogen/Meta-Transaction-Risk-Classification
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          First Python Project - Meta Transaction Risk Classification
        description: | # this will include new lines to allow paragraphs
          New to Python, this experimental notebook analyzes pre-cleaned data, 
          then explores testing 4 model types with a range of hyperparameters
          utilizing Halving Grid Search and Bayesian Optimization. The implementation is general
          and can easily be adapted to most any model available in scikit learn. Though not 
          advisable given the input models, I then test Stacking and Voting classifiers as 
          ensemble models. More projects will be added to this project section.

          Project Keywords: Scikit Learn, Pandas, Seaborn, Numpy, LightGBM, Machine Learning Pipeline

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: E Source (Wiland will be added next)
        link: https://www.esource.com/
        # link_text: boringcompany.com
        sub_title: Data Scientist
        caption: April 2022 - November 2023
        quote: >
          May leave this section blank
        description: | # this will include new lines to allow paragraphs
            May give alternate description to resume bullet points. But for now: 
            ● Built ETL pipelines to convene, clean, and engineer features from high-dimensional data across millions of utility customers and premises. \n
            ● Developed fine-tuned model pipelines to give premise level predictions, classify end-use, and cluster customer program impact profiles. \n
            ● Led collaboration with data engineering that improved critical premise append matching algorithm’s accuracy 14% and accelerated processing time by 6x. \n
            ● Developed and automated data ingestion for interactive dashboard that monitored high volume Advanced Meter Infrastructure data, facilitating daily insight into client data quality. \n
            ● Created informative and story driven presentations, with key decisions emphasized by statistics and clear visualizations, giving clients understanding of methodology and results. \n

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Colorado State University
        caption: 2016 - 2019
        sub_title: BSc Statistics
        quote: >
          Probably remove this quote section
        description: | # this will include new lines to allow paragraphs
          Began at community college with mediocre grades. 
          In final semesters with challenging Statistics classes made the Dean's List
          and was Vice President of the Statistics Club

  - title: About Me Section
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in programming, machine learning, and organizations. 
      - There will be a Leetcode Section
      - There will be a Leetcode Section
      - There will be a Leetcode Section
      - Triathlon

      Look at this cool image (probably remove this)
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
